/**
 * Created by Zipeng Liu on 2016-11-30.
 */

export const FETCH_INSTANCE_REQUEST = 'FETCH_INSTANCE_REQUEST';
export const FETCH_INSTANCE_SUCCESS = 'FETCH_INSTANCE_SUCCESS';
export const FETCH_INSTANCE_FAILURE = 'FETCH_INSTANCE_FAILURE';

export const TOGGLE_LABEL = 'TOGGLE_LABEL';
export const TOGGLE_TRANSITIVITY_MODE = 'TOGGLE_TRANSITIVITY_MODE';
export const TOGGLE_HIGHLIGHT_INVARIANT_NODE = 'TOGGLE_HIGHLIGHT_INVARIANT_NODE';

export const PATH_SEGMENT_READY = 'PATH_SEGMENT_READY';
export const TOGGLE_CLICK_STATE = 'TOGGLE_CLICK_STATE';
export const CHANGE_DIFF_FUNC = 'CHANGE_DIFF_FUNC';
export const TOGGLE_VARIABLE_LIST = 'TOGGLE_VARIABLE_LIST';
export const TOGGLE_DUMP_VARIABLE = 'TOGGLE_DUMP_VARIABLE';
export const START_SELECTION = 'START_SELECTION';
export const END_SELECTION = 'END_SELECTION';
export const CHANGE_SELECTION = 'CHANGE_SELECTION';